.PHONY: all install

all:
	$(MAKE) -C balance
	$(MAKE) -C bitdiff
	$(MAKE) -C byteat
	$(MAKE) -C corrupt
	$(MAKE) -C maybe
	$(MAKE) -C n7m

install:
	$(MAKE) -C apdiff install
	$(MAKE) -C balance install
	$(MAKE) -C bitdiff install
	$(MAKE) -C byteat install
	$(MAKE) -C corrupt install
	$(MAKE) -C git-ls install
	$(MAKE) -C lines install
	$(MAKE) -C maybe install
	$(MAKE) -C n7m install
	$(MAKE) -C pip-upgrade-all install
	$(MAKE) -C ruler install
	$(MAKE) -C termdraw install
	$(MAKE) -C trimline install
	$(MAKE) -C update-all install
