#!/bin/sh
# Usage: docker-cleanup
# Remove stopped and data-only Docker containers.

docker ps -a --no-trunc | egrep '((weeks)|(months)) ago' | awk '{print $1}'
docker ps -a --no-trunc | egrep '((weeks)|(months)) ago' | awk '{print $1}' | xargs --no-run-if-empty docker rm

# Alternatives:
# docker ps -a | awk 'NR > 1 {print $1}' | xargs docker rm
# docker images | grep "<none>" | awk '{print $3}' | xargs docker rmi
# docker ps -a | grep 'weeks ago' | awk '{print $1}' | xargs --no-run-if-empty docker rm
