#!/bin/sh

WAN_IP=$(curl icanhazip.com 2>/dev/zero)
PING_RETCODE=$(ping -c1 google.com 1>/dev/zero 2>/dev/zero ; echo $?)

if [ "$PING_RETCODE" = "0" ] ; then
	NETWORKNAME="$WAN_IP@$(nmcli con show --active | grep wlp7s0 | cut -d' ' -f1)"
else
	NETWORKNAME="No network"
fi

echo "$NETWORKNAME"
