#!/bin/sh
# Usage: single-urxvt [URXVT_ARGS...]
# Launch a singleton urxvt instance, or minimize/maximize already running one
#
# This script is courtesy of forums.debian.net user jw013:
# http://forums.debian.net/viewtopic.php?f=16&t=60374

# single_urxvt: emulates quake terminal functionality
# designed for use with openbox and wmctrl
# make sure wmctrl is installed

SINGLE_URXVT_WMCLASS=single-urxvt

# make sure wmctrl exists
wmctrlpath="$(which wmctrl 2>/dev/null)"
if ! [ -x "$wmctrlpath" ] ; then
	echo Error: required dependency wmctrl not found. >&2
	exit 1
fi

active_window_id=\
"$(xprop -root | sed -n -e '/^_NET_ACTIVE/s/^[[:print:]]\{40\}//p')"

# test: true if active window has WM_CLASS $SINGLE_URXVT_WMCLASS
if xprop -id "$active_window_id" 2>/dev/null | \
	grep -q '^WM_CLASS(STRING)[[:print:]]*'"$SINGLE_URXVT_WMCLASS"
then
	# hide active quake rxvt
	wmctrl -i -r "$active_window_id" -b add,hidden
	xdotool windowminimize "$(xdotool getactivewindow)"
elif ! wmctrl -R "$SINGLE_URXVT_WMCLASS" -x ; then
# use the wmctrl to both focus and raise quake terminal as well as
# test if it is already running; wmctrl returns nonzero/false if no matching
# window is found, so we have to start it
	urxvt -name "$SINGLE_URXVT_WMCLASS" "$@" &
fi
