#!/usr/bin/env python

# TODO: Context options, like -ABC in grep, but with symbols instead of lines
# TODO: Tokenize file paths, so paths like "01 - Some long episode title.ext"\
# and "12 - Some other long episode title.ext" don't confuse apdiff and/or\
# require a small cutoff which won't probably work anyway

import os
import sys
import difflib
import fnmatch
import itertools


MAX_NEIGHBORS   = int(os.environ.get('MAX_NEIGHBORS', 1000))
NEIGHBOR_CUTOFF = float(os.environ.get('CUTOFF', 0.7))
GLOB            = str(os.environ.get('GLOB', '*'))


def apdiff_process(arg):
    basename      = os.path.basename(arg)
    parent_path   = os.path.abspath(os.path.join(arg, os.pardir))
    sibling_files = [f for f in os.listdir(parent_path) if fnmatch.fnmatch(f, GLOB)]
    close_paths   = difflib.get_close_matches(basename,
                                              sibling_files,
                                              MAX_NEIGHBORS,
                                              NEIGHBOR_CUTOFF)
    diff_subseqs = []

    for neighbor in close_paths:
        same    = lambda s: s.startswith('  ')
        deleted = lambda s: s.startswith('- ')
        diff = list(difflib.Differ().compare(neighbor, basename))
        diff = list(itertools.dropwhile(same, diff))
        diff.reverse()
        diff = list(itertools.dropwhile(same, diff))
        diff.reverse()
        diff = ''.join(list([i[2:] for i in diff if not deleted(i)]))
        diff_subseqs.append(diff)

    print(max(diff_subseqs, key=len))


if __name__ == '__main__':
    for argument in sys.argv[1:]:
        if os.path.exists(argument):
            apdiff_process(argument)
