.PHONY: all install

all:
	true

install: all
	$(MAKE) -C git-clone-github-user install
	$(MAKE) -C git-ls                install
	$(MAKE) -C git-repo-list         install
	$(MAKE) -C git-stat-atr          install
