#!/bin/sh
# Usage: clone-github-user USER [GIT_CLONE_OPTS...]
# Clone all repositories of a Github user to the working directory.

PER_PAGE=200
USER="$1"

shift 1

curl -s "https://api.github.com/users/$USER/repos?per_page=$PER_PAGE" \
"https://api.github.com/orgs/$USER/repos?per_page=$PER_PAGE" | \
jq -r '.[].html_url?' | sort | uniq | parallel git clone "$@"
