#!/usr/bin/env ruby

require 'rubygems'
require 'capybara'
require 'capybara/poltergeist'
require 'net/http'
require 'open-uri'
require 'optparse'
require 'ostruct'
require 'uri'
require 'fileutils'

TIMEOUT       = 60
STDNULL       = File.open(File::NULL, 'w')

module Imgur
  class Downloader
    def download(url, opts)
      session = Capybara::Session.new(:poltergeist)
      session.visit(url)
      images = []

      post_id = session.current_url[/(?<=\/)(\w*)$/, 1]
      post_title = session.find(:xpath, "//title").text.gsub("- Album on Imgur", "").strip

      subdir = "#{post_id} #{"- " + post_title unless post_title =~ /Imgur: The most awesome images on the Internet/}".strip
      path = opts.path
      path = subdir if path == "."

      session.visit(session.current_url.gsub(/gallery/, "a").gsub(/(?<!\/layout\/grid)$/, '/layout/grid'))

      expected_imgs = Integer session.find(:xpath, "//h2[contains(text(),'image')]").text[/(\d+) image(s)?$/, 1]
      STDERR.puts("Expecting #{expected_imgs} images")

      loop do
        STDERR.puts("Scrolling down")
        session.execute_script('window.scrollBy(0,100000)')
        sleep 2
        images = session.all(:xpath, "//div[@class='posts']/div[.//img]")
        STDERR.puts("Found #{images.size} images out of expected #{expected_imgs}")
        break unless images.size < expected_imgs
      end

      FileUtils::mkdir_p(path)

      images.each_with_index do |img, index|
        image_url = img.find(:xpath, ".//img")[:src].gsub("b.", ".")
        request   = open(image_url)
        basename  = File.basename(URI.parse(image_url).path).tr("/\000", "")
        filename  = "#{index+1} - #{basename}"
        puts("#{File.join(path, filename)}")
        IO.copy_stream(request, File.join(path, filename))
      end
    end
  end
end

cli_options  = OpenStruct.new

OptionParser.new do |option|
  option.on('-d PATH', '--dir PATH') {|o| cli_options.path = o}
end.parse!

cli_options.path = '.' unless cli_options.path

Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, {js_errors: false, timeout: TIMEOUT, phantomjs_logger: STDNULL})
end

Capybara.run_server              = false
Capybara.current_driver          = :poltergeist
Capybara.ignore_hidden_elements  = false

if ARGV.empty? then
  Imgur::Downloader.new.download(ask("Album url: "), cli_options)
end

ARGV.each do |arg|
  Imgur::Downloader.new.download(arg, cli_options)
end
