#!/bin/sh

STDIN="$(cat)"
RINGFILE="$1"
RINGFILE_LINE_COUNT="$(wc -l < "$RINGFILE")"

if [ -z "$RINGFILE" ]; then
	echo "$(basename "$0"): ring file not specified, refer to bacontools documentation" 1>&2
	exit 1
fi

if [ ! -e "$RINGFILE" ]; then
	echo "$(basename "$0"): file $RINGFILE does not exist, refer to bacontools documentation" 1>&2
	exit 1
fi

echo "$STDIN"  >> "$RINGFILE"
tail -"$RINGFILE_LINE_COUNT" "$RINGFILE" | sponge "$RINGFILE"
