#!/bin/sh

set -x

STDIN="$(cat)"
RINGFILE="$1"
RINGFILE_LINE_COUNT="$(wc -l < "$RINGFILE")"
LINE_COUNT="$(echo "$STDIN" | wc -l)"

if [ -z "$RINGFILE" ]; then
	echo "$(basename "$0"): ring file not specified, refer to bacontools documentation" 1>&2
	exit 1
fi

if [ ! -e "$RINGFILE" ]; then
	echo "$(basename "$0"): file $RINGFILE does not exist, refer to bacontools documentation" 1>&2
	exit 1
fi

if [ "$LINE_COUNT" -gt "$RINGFILE_LINE_COUNT" ]; then
	STDIN="$(printf "%s" "$STDIN" | tail -"$RINGFILE_LINE_COUNT")"
fi

if [ "$LINE_COUNT" -eq "$RINGFILE_LINE_COUNT" ]; then
	printf "%s" "$STDIN" > "$RINGFILE"
	exit 0
fi

LINES_TO_ECHO="$(( RINGFILE_LINE_COUNT - LINE_COUNT ))"

CONTENT="$(tail -"$LINES_TO_ECHO" "$RINGFILE")"
echo "$CONTENT" > "$RINGFILE"
echo "$STDIN"  >> "$RINGFILE"
