#!/bin/sh
# Usage: git-stat-adr [GIT DIFF --STAT ARGUMENT...]
# Sort a 'git diff --stat' output by total/added lines ratio.

LASTLINE="$(git diff --stat --color "$@" | tail -1)"

git diff --stat --color "$@" | head -n-1 |\
awk '{printf("%s %s\n", (gsub("+","+")+0.000001)/(gsub("+","+")+gsub("-","-")), $0)}' |\
sort -h |\
cut -d' ' -f2-

echo "$LASTLINE"
