.PHONY: all install preptrack-install vidinfo-install

all:

install: preptrack-install vidinfo-install

preptrack-install:
	$(MAKE) -C preptrack install

vidinfo-install:
	$(MAKE) -C vidinfo install
