.PHONY: all install preptrack-install togif-install vidinfo-install

all:

install: preptrack-install togif-install vidinfo-install

preptrack-install:
	$(MAKE) -C preptrack install

togif-install:
	$(MAKE) -C togif install

vidinfo-install:
	$(MAKE) -C vidinfo install
