.TH imgur-dl 1 "imgur-dl" "26 Aug 2016" "version 2016.08.26"

.SH NAME
imgur-dl - download albums from imgur.com

.SH SYNOPSIS
imgur-dl\~[--dir=\fBPATH\fP]\~[\fBURL\fP...]

.SH DESCRIPTION
\fBimgur-dl\fP downloads one or several Imgur albums to the current directory.
If no URL is specified on the command line, Imgur interactively prompts the
user instead.

.SH OPTIONS
.TP
--dir=\fBPATH\fP, -d\fBPATH\fP
Override default save path (which is a subdirectory of the working directory
with the name equal to the album's title) and save to \fBPATH\fP. Note that
\fBimgur-dl\fP won't create a subdirectory in this case, which means that
\fBimgur\~-d.\~URL\fP (or \fBimgur -d$(pwd) URL\fP) and \fBimgur\~URL\fP are
not equivalent: the first two commands download all images to the current
directory, while the third command creates a subdirectory named "\fBID\fP[ -
\fBNAME\fP]", where \fBID\fP is the unique album identifier and \fBNAME\fP is
an optional album title which does not always appear on the page.

.SH DEPENDENCIES
\fBphantomjs\fP, \fBruby\fP, \fBcapybara\fP, \fBhighline\fP,
\fBopen_uri_redirections\fP

.SH AUTHOR
Developed by Ilya Terentyev <bacondropped@gmail.com> as a part of the
\fBbacontools\fP package <https://gitlab.com/bacondropped/bacontools>.

.SH LICENSE
\fBimgur-dl\fP is distributed under the terms of the MIT license.

.SH SEE ALSO
\fBbacontools\fP(7)
