#!/usr/bin/env python3
# Usage: humansize [BYTES]
# Convert size in bytes to a less precise human-readable string.

import sys
import math


BINARY_BASE = 1024
BINARY_PREFIXES = ['', 'Ki', 'Mi', 'Gi', 'Ti', 'Pi', 'Ei', 'Zi', 'Yi']
BYTE = "B"


if __name__ == '__main__':
    bytes = int(sys.argv[1])

    i = math.floor(math.log(bytes, BINARY_BASE))

    if i > len(BINARY_PREFIXES):
        i = len(BINARY_PREFIXES)

    print("{0:.1f} {1}{2}".format(1.0 * bytes / BINARY_BASE**i, BINARY_PREFIXES[i], BYTE))
