#!/usr/bin/env python3
# Usage: humansize [BYTES]
# Convert size in bytes to a less precise human-readable string.

import sys
import math


BINARY_BASE = 1024
BINARY_PREFIXES = ['', 'Ki', 'Mi', 'Gi', 'Ti', 'Pi', 'Ei', 'Zi', 'Yi']
BYTE = "B"


if __name__ == '__main__':
    bytes = int(sys.argv[1])

    try:
        i = math.floor(math.log(bytes, BINARY_BASE))
    except ValueError:
        i = 0

    if i > len(BINARY_PREFIXES):
        i = len(BINARY_PREFIXES)

    number = "{0:.1f}".format(1.0 * bytes / BINARY_BASE**i).replace(".0", "")

    print("{} {}{}".format(number, BINARY_PREFIXES[i], BYTE))
