#!/bin/sh
# Usage: wget-parallel URL...
# Fetch multiple urls with wget via GNU parallel.
#
# ENVIRONMENT:
# PARALLEL_ARGS       A list of supplementary options for parallel. It will be
#                     expanded once, so spaces within options must be escaped
#                     with a literal slash or single quotes.
# WGET_ARGS           A list of supplementary options for wget. Same concerns
#                     as with PARALLEL_ARGS apply.

cat_stdin() {
	if [ ! -t 0 ]; then
		cat
	fi
}

# shellcheck disable=SC2086
( if [ "$#" -gt 0 ]; then printf "%s\n" "$@" ; fi ; cat_stdin ) | \
sort | \
uniq | \
parallel $PARALLEL_ARGS -- wget -nv -nc $WGET_ARGS
