#!/bin/sh
# Usage: [command | ] vimless [-N] [FILE...]
# Pass output of vimcat (from vimpager package) to less.
#
# OPTIONS:
#  -N                 Pass -N to less, which will make it print line numbers
#
# TODO: position-independent flags, refer to the "right now" comment

vimcat_less() {
	vimcat -o - "$@" | sed 's/$/\x1B[0m/' | less -r $LESS_N
}

LESS_N=""

# Exit if no arguments were passed and stdin is attached to a tty
if [ "$#" = "0" -a -t 0 ] ; then
	echo "File argument[s] or stdin input required" 1>&2
	echo "Usage: [command | ] $(basename "$0") [-N] [FILE...]" 1>&2
	exit 1
fi

# XXX: right now, 'vimless -N FILE' is supported while 'vimless FILE -N' is not
while getopts N f ; do
	case "$f" in
		N) LESS_N=1 ;;
	esac
done

shift "$(( OPTIND - 1 ))"

if [ "$LESS_N" = "1" ] ; then
	LESS_N="-N"
fi

if [ ! -t 0 ] ; then
	vimcat_less
else
	for FILE in "$@" ; do
		vimcat_less "$FILE"
	done
fi
