#!/bin/sh
# Usage: git-force-pristine
# Remove all Git untracked files and checkout the repository.

set -e

PROGRAM_NAME="$(basename "$0")"

if [ -n "$1" ]; then
	cd "$1" || ( echo "$PROGRAM_NAME: could not cd to '$1'" 1>&2 && exit )
fi

GIT_ROOT="$(git rev-parse --show-toplevel)"
cd "$GIT_ROOT" || ( echo "$PROGRAM_NAME: could not cd to '$GIT_ROOT'" 1>&2 && exit )

git clean -dffx
git gc --auto
git checkout -- .
