#!/bin/sh
# Usage: keepalive [PROGRAM] [ARGS...]
# Restart command line if no instances of it are running.
#
# Environment:
# INTERVAL            Sleeping interval between each ps check (default 10s).
#
# Requirements:
# sh
# ps
# nohup
# sleep
# wc

if [ "$#" = "0" ]; then
	echo "No command line specified, exiting" 1>&2
	echo "Usage: $(basename "$0") [PROGRAM] [ARGS...]" 1>&2
	exit 1
fi

sigint_trap() {
	echo "SIGINT received, exiting" 1>&2
	exit 0
}

trap sigint_trap INT

INTERVAL="${INTERVAL-10s}"

while true ; do
	if [ "$(ps --no-headers -fC "$1" | wc -l)" = 0 ]; then
		echo "$(date): restarting $*" 1>&2
		nohup "$@" 1>/dev/null 2>/dev/null &
	fi

	sleep "$INTERVAL"
done
