.TH termdraw 1 "termdraw"

.SH NAME
termdraw \- an ASCII/Unicode art data visualizer

Termdraw is a command line interface to Python termdraw library. It requires
Python 3.

.SH SYNOPSIS
termdraw [options] file.csv [file2.csv [...]]

.SH OPTIONS
.TP
\-h, \-\-help
Print help message.

.TP
\-n, \-\-no\-interpolation
Disable midpoint graph interpolation.

.TP
\-i, \-\-interpolation
Enable midpoint graph interpolation.

.TP
\-s, \-\-solid
Draw solid graph (with continuous block columns below data points).

.TP
\-p, \-\-point
Draw point graph (without supporting columns).

.TP
\-a, \-\-ascii
Only use characters from ASCII charset.

.TP
\-\-debug
Print debug info.

.SH SOURCE
Source can be obtained at https://github.com/bacondropped/termdraw.git

.SH AUTHOR
Ilya Terentyev <bacondropped@gmail.com>
