.PHONY: all install

all:

install:
	$(MAKE) -C bindump        install
	$(MAKE) -C cate           install
	$(MAKE) -C checkreboot    install
	$(MAKE) -C cptemp         install
	$(MAKE) -C cursorwiggle   install
	$(MAKE) -C devbup         install
	$(MAKE) -C devrestore     install
	$(MAKE) -C docker-cleanup install
	$(MAKE) -C du1            install
	$(MAKE) -C keepalive      install
	$(MAKE) -C netinfo        install
	$(MAKE) -C single-urxvt   install
	$(MAKE) -C userls         install
	$(MAKE) -C xclip-tofile   install
	$(MAKE) -C zerofile       install
