.PHONY: all install

all:
	$(MAKE) -C balance
	$(MAKE) -C n7m
	$(MAKE) -C readable

install:
	$(MAKE) -C balance install
	$(MAKE) -C lines install
	$(MAKE) -C morseconv install
	$(MAKE) -C n7m install
	$(MAKE) -C readable install
	$(MAKE) -C ringcat install
	$(MAKE) -C ruler install
	$(MAKE) -C trimline install
	$(MAKE) -C vimless install
